### getDevelopers
GET {{baseUrl}}/developer
Accept: application/json

### saveDeveloper
POST {{baseUrl}}/developer
Accept: application/json
Content-Type: application/json

{
  "id": 1,
  "nickName": "Carlo"
}
