### getDevelopers
GET {{baseUrl}}/developer
Accept: application/json

### saveDevelopers
POST {{baseUrl}}/developer
Accept: application/json
Content-Type: application/json

[
  {
    "id": 1,
    "nickName": "Carlo"
  },
  {
    "id": null,
    "nickName": "Andrea"
  }
]
