### getPairs
GET {{baseUrl}}/team/{{sprintId}}/pair
Accept: application/json

### savePairs
POST {{baseUrl}}/team/{{sprintId}}/pair
Accept: application/json
Content-Type: application/json

[
  {
    "id": 1,
    "members": [
      {
        "id": 1,
        "nickName": "Carlo"
      },
      {
        "id": 2,
        "nickName": "Andrea"
      }
    ]
  },
  {
    "id": 2,
    "members": [
      {
        "id": 2,
        "nickName": "Andrea"
      },
      {
        "id": 1,
        "nickName": "Carlo"
      }
    ]
  }
]
