### getTeam
GET {{baseUrl}}/team/{{teamId}}
Accept: application/json

### saveTeam
POST {{baseUrl}}/team
Accept: application/json
Content-Type: application/json

{
  "id": {{teamId}},
  "name": "An awesome team name",
  "developers": [
    {
      "id": 5709113312935936,
      "nickName": "Dev1"
    },
    {
      "id": 5743670015819776,
      "nickName": "Dev2"
    },
    {
      "id": 5671636300726272,
      "nickName": "Dev3"
    }
  ]
}
